<?php
/** @var array $rawItems */

?>
<div class="grids" style="margin-top: 10px">
    <table class="data-table children-items-tables" cellspacing="0">
        <thead>
            <tr class="headings">
                <th class="data-grid-th" style="width:250px"><?= __("Product Name") ?></th>
                <th class="data-grid-th" style="width:200px"><?= __("Product SKU") ?></th>
                <th class="data-grid-th" style="width:200px"><?= __("Ordered Quantity") ?></th>
            </tr>
        </thead>

        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($rawItems as $productData): ?>
            <tr class="<?php echo(++$i % 2 ? 'even' : 'odd') ?>">
                <td><?= $productData["name"] ?></td>
                <td><?= $productData["sku"] ?></td>
                <td><?= (int) $productData["ordered_qty"] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
