<?php
/**
 * Password Protected
 *
 * @category    Addify
 * @package     Addify_PasswordProtected
 * @author      Addify
 * @Email       addifypro@gmail.com
 *
 */
$pageSetting = $block->helper->getpageSetting();

?>
<div class="login-container">
    <div class="block block-customer-login">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php echo $pageSetting['heading'] ?></strong>
        </div>
    <div class="block-content">
            <form class=" form form-login" method="post" action="<?php echo $block->submiturl() ?>">

                <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <div class="field note"></div>

                    <div class="field required">
                    <label for="password" class="label"><?php echo $pageSetting['label'] ?>&nbsp;</label>
                        <div class="control">
                    <input class=" input-text" type="password" name="pps_password" id="password" autocomplete="current-password" required="true" />
                        </div>
                    </div>

                    <div class="actions-toolbar">
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php echo $pageSetting['button'] ?></span></button></div>

                    </div>



                </fieldset>
            </form>
        </div>
    </div>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php echo $pageSetting['rightheading'] ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?php echo $block->filterOutputHtml($pageSetting['description']) ?></p>

    </div>
</div>

    ​
