<?php
/** @var \Bss\BrandRepresentative\Block\Category\MostViewedCollector $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php
$needCollectTraffic = $block->isNeedCollectTraffic();
?>

<?php if ($needCollectTraffic) :?>
<script type="text/x-magento-init">
    {
        "body": {
            "Bss_BrandRepresentative/js/brand-traffic-collector": {
                "addNewVisitUrl": "<?= $escaper->escapeUrl($block->getAddNewVisitUrl()) ?>"
            }
        }
    }
</script>
<?php endif; ?>
