<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_BrandCategoryLevel
 * @author     Extension Team
 * @copyright  Copyright (c) 2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Magento\Catalog\Block\Category\View;
use Magento\Catalog\Model\Category;

?>
<?php
/**
 * Category view template
 *
 * @var $block View
 */

$currentCategory = $block->getViewModel()->getCurrentCategory();
$levelCategory = $currentCategory->getLevel();
$childCategories = $block->getViewModel()->getChildCategories();
if ($levelCategory < 4): ?>
    <?php if (!empty($childCategories)): ?>
        <h2><?=__("Brand's Categories")?></h2>
        <div class="products wrapper grid columns3 products-grid   ">
            <ol class="filterproducts products list items product-items ">
                <?php /* @var Category $category*/?>
                <?php foreach ($childCategories as $category): ?>
                    <li class="item product product-item">
                        <div class="product-item-info type1" data-container="product-grid">
                            <div class="product photo product-item-photo">
                                <a href="<?= $block->escapeUrl($category->getUrl()) ?>" tabindex="-1">
                                    <?php
                                    $outputHelper = $block->getViewModel()->getCatalogOutputHelper();
                                    $baseUrl = rtrim($block->getViewModel()->prepareBaseUrl(), '/');
                                    $_imgHtml   = '';
                                    if ($_imgUrl = $category->getImageUrl()) {
                                        $_imgHtml = '<img src="' . $block->escapeUrl($baseUrl . $_imgUrl) . '" />';
                                        $_imgHtml = $outputHelper->categoryAttribute($category, $_imgHtml, 'image');
                                        /* @escapeNotVerified */ echo $_imgHtml;
                                    } else {
                                        $_imgUrl = $block->getViewModel()->preparePlaceholder();
                                        $_imgHtml = '<img src="' . $block->escapeUrl($_imgUrl) . '" />';
                                        $_imgHtml = $outputHelper->categoryAttribute($category, $_imgHtml, 'image');
                                        /* @escapeNotVerified */ echo $_imgHtml;

                                    }
                                    ?>
                                </a>
                            </div>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="<?= $block->escapeUrl($category->getUrl()) ?>">
                                        <span><?= __($category->getName()) ?></span>
                                    </a>
                                </strong>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>
<?php else: ?>
    <?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
        <h2><?=__($currentCategory->getOriginalName())?></h2>
        <?= $block->getProductListHtml() ?>
    <?php endif; ?>
<?php endif; ?>

