<?php
    $product_view = $this->getConfig('porto_settings/category');
    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    $_loggedin = $this->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->isLoggedIn();
    if( $_loggedin ) {
        if($block) {
            $block->setBlockId($product_view['side_custom_block']);
        }
        if($block){
            echo $block->toHtml();
        }
    }
    ?>