<?php
    $product_view = $this->getConfig('porto_settings/category');
    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    $isLoggedIn = $this->getLayout()
        ->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->isLoggedIn();
?>
<?php if ($isLoggedIn):
        if ($block) {
            $block->setBlockId($product_view['side_custom_block']);
            echo $block->toHtml();
        }
        ?>
<?php else: ?>
    <div class="not-logged-in content-sche btn-content">
        <p class="text-login"><?= __('You need to login for further action!') ?></p>
        <div class="to-login action wrapper">
            <a class="btn-sidebar sche" href="<?= $block->getUrl('customer/account/login') ?>">
                <?= __('Login') ?>
            </a>
            
        </div>
    </div>
<?php endif; ?>
