
<div class="brands-list-all">
<div class="content-featured-brand">
    <div class="container">
        <h4 class="title-nomal">Featured</h4>
        <div class="products wrapper grid columns5 products-grid   ">
        <ol class="filterproducts products list items product-items ">
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/redecan-sell-sheet.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/digital-download-test.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg"  alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
        </ol>
    </div>
</div>
</div>






<div class="content-list">
<div class="container">
<div id="layer-product-list" class="list-brands">
    <div class="toolbar toolbar-products" data-mage-init="{&quot;productListToolbarForm&quot;:{&quot;mode&quot;:&quot;product_list_mode&quot;,&quot;direction&quot;:&quot;product_list_dir&quot;,&quot;order&quot;:&quot;product_list_order&quot;,&quot;limit&quot;:&quot;product_list_limit&quot;,&quot;modeDefault&quot;:&quot;grid&quot;,&quot;directionDefault&quot;:&quot;asc&quot;,&quot;orderDefault&quot;:&quot;position&quot;,&quot;limitDefault&quot;:12,&quot;url&quot;:&quot;http:\/\/devm2php74.tk\/one2oneretail-hue\/default\/redecan\/sell-sheets.html&quot;,&quot;formKey&quot;:&quot;63RHzmrMwCTyGFw9&quot;,&quot;post&quot;:false}}">
        <div class="toolbar-sorter sorter">
            <label class="sorter-label" for="sorter">Sort By</label>
            <select id="sorter" data-role="sorter" class="sorter-options">
                <option value="position" selected="selected">
                    Position            </option>
                <option value="name">
                    Product Name            </option>
                <option value="price">
                    Price            </option>
            </select>
            <a title="Set Descending Direction" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
                <span>Set Descending Direction</span>
            </a>
        </div>

    </div>
    <div class="products wrapper grid columns5 products-grid   ">
        <ol class="filterproducts products list items product-items ">
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/redecan-sell-sheet.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/digital-download-test.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
            <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
             <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
             <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
             <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
             <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
             <li class="item product product-item">                
                <div class="product-item-info type1" data-container="product-grid">
                    <div class="product photo product-item-photo">
                        <a href="http://devm2php74.tk/one2oneretail-hue/default/test-3.html" tabindex="-1">
                            <img class="product-image-photo default_image porto-lazyload" data-src="http://devm2php74.tk/one2oneretail-hue/pub/media/catalog/category/brand-2.jpg" alt="">
                        </a>
                    </div>
                </div>
            </li>
        </ol>
    </div>
    </div>
</div>
</div>
</div>