<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AdminPreview
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$title = __('Edit Static Block');
?>
<a class="click-me bss-adminpreview-backend" target="_blank" href="<?php echo $url ?>"><?php echo $title ?></a>
<style>
.bss-adminpreview-backend {background-color: #f7531b;color: #fff !important;display: inline-block;font-weight: bold;padding: 3px 8px!important;position: relative;z-index: 999;}
</style>
