<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_BrandRepresentative
 * @author     Extension Team
 * @copyright  Copyright (c) 2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Bss\BrandRepresentative\Block\Brand\Pages\BrandList;

/**
 * @var $block BrandList
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div class="content-list">
    <div class="container">
        <div id="layer-brand-list" class="list-brands" data-mage-init='{"Bss_BrandRepresentative/js/scroll-to-brand-list":{}}'>
            <h4 class="title-nomal"><?= $block->getTitle()?></h4>
            <?= $block->getToolbarHtml() ?>
            <div class="products wrapper grid columns5 products-grid">
                <ol class="filterproducts products list items product-items">
                    <?php $categories = $block->getCategories(); ?>
                    <?php foreach ($categories->getItems() as $category): ?>
                        <li class="item product product-item">
                            <div class="product-item-info type1" data-container="product-grid">
                                <div class="product photo product-item-photo">
                                    <a href=<?= $category->getUrl() ?> tabindex="-1">
                                        <?php if ($category->getImageUrl()): ?>
                                            <?php $imageResize = $block->getCategoryImage($category) ?>
                                            <img class="product-image-photo default_image porto-lazyload" data-src="<?= $escaper->escapeUrl($imageResize) ?>" alt="<?= $category->getName(); ?>" />
                                        <?php else: ?>
                                            <img class="product-image-photo default_image porto-lazyload" data-src="<?= $escaper->escapeUrl($block->getPlaceHolderImage()) ?>" alt="<?= $category->getName(); ?>" />
                                        <?php endif; ?>
                                        <span><?php echo $category->getName(); ?></span>
                                    </a>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?= $block->getToolbarHtml() ?>
        </div>
    </div>
</div>
