<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_BrandRepresentative
 * @author     Extension Team
 * @copyright  Copyright (c) 2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php $report = $block->getReport(); ?>
<?php if ($report): ?>
<div class="report-listing-wrapper">
    <table class="email-items">
        <thead>
            <tr>
                <th class="row-order-id">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Order ID')) ?>
                </th>
                <th class="row-sku">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Product SKU')) ?>
                </th>
                <th class="row-product-name">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Product Name')) ?>
                </th>
                <th class="row-product-type">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Product Type')) ?>
                </th>
                <th class="row-qty">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Ordered Quantity')) ?>
                </th>
                <th class="row-time">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Ordered Time')) ?>
                </th>
                <th class="row-adress">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Address')) ?>
                </th>
                <th class="row-city">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('City')) ?>
                </th>
                <th class="row-province">
                    <?= /* @escapeNotVerified */  $block->escapeHtml(__('Province')) ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($report as $key => $rowItem): ?>
                <tr class="row-data-<?=$key?>">
                    <?php foreach ($rowItem as $colKey => $colValue): ?>
                        <td class="col-data-<?=$colKey?>">
                            <?= /* @escapeNotVerified */  $block->escapeHtml(__((string)$colValue)) ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php else: ?>
<p>Empty Report! Please contact us for more information!</p>
<?php endif; ?>
