<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Bss\CategoryAttributes\Block\Category\BrandContact $block */
?>
<div class="content-sche btn-content">
    <div class="action wrapper">
        <a class="btn-sidebar sche" href="#"
           data-mage-init='{"Bss_CategoryAttributes/js/view/show-contact-form": <?= $escaper->escapeHtmlAttr($block->getJsConfigData("schedule_visit_embedded_link")) ?>}'>
            <?= $escaper->escapeHtml(__("RESCHEDULE VISIT")) ?>
        </a>
    </div>
</div>
<div class="content-sche btn-content">
    <div class="action wrapper">
        <a class="btn-sidebar contact" href="#"
           data-mage-init='{"Bss_CategoryAttributes/js/view/show-contact-form": <?= $escaper->escapeHtmlAttr($block->getJsConfigData("contact_us_embedded_link")) ?>}'>
            <?= $escaper->escapeHtml(__("CONTACT US")) ?>
        </a>
    </div>
</div>
