<div class="category-top">
	<div class="row">
		<div class="col-md-3"><?php echo $block->getChildHtml('category.image');?></div>
		<div class="col-md-9 col-right">
			<div class="name-category">
				<h2 class="title-category title-nomal">
					<?php if ($_categoryname = $block->getCurrentCategory()->getName()): ?>
					   	<?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_categoryname, 'name') ?>
					<?php endif; ?>

				</h2>
			</div>
			<?php if ($_description = $block->getCurrentCategory()->getShortDescription()): ?>
			   	<?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'short_description') ?>
			<?php endif; ?>
		</div>
	</div>
</div>
